coverage:
  status:
    project:
      default:
        # basic
        target: 85%
        threshold: 3%
        base: auto
    patch:
      default:
        # basic
        target: 85%
        threshold: 3%
        base: auto